#!/usr/bin/env python3
"""
Run doctests for fountain module.
"""
import doctest

import fountain


def test_fountain():
    """ None: Raise error if any doctests failed. """
    assert not doctest.testmod(fountain).failed
    print("OK fountain")


if __name__ == "__main__":
    test_fountain()
